export const Voter = {
    email: '',
    password: '',
    state: '',
    district: '',
    area: '',
    firstName: '',
    lastName: '',
    photograph: '',
    contact: '',
    contactNumber: '',
    emailof: '',
    relativeFirstName: '',
    relativeLastName: '',
    aadhaarNumber: '',
    dob: '',
    docProofName: '',
    aadhaarPhoto: '',
    house: '',
    areaLocality: '',
    villageTown: '',
    post: '',
    pincode: '',
    tehsil: '',
    proofOfResidence: '',
    birthVillage: '',
    birthState: '',
    birthDistrict: '',
    livingSince: '',
    placeOfSignature: ''
};
module.exports = Voter;